package voxpopuli.action;
public enum Action
{
	ECLIPSE_CONTEXTINFORMATION("org.eclipse.ui.edit.text.contentAssist.contextInformation","Eclipse Context Information"),
	ECLIPSE_COPY("org.eclipse.ui.edit.copy","Eclipse Copy"),
	ECLIPSE_CUT("org.eclipse.ui.edit.cut","Eclipse Cut"),
	ECLIPSE_DELETE("org.eclipse.ui.edit.delete","Eclipse Delete"),
	ECLIPSE_FINDNEXT("org.eclipse.ui.edit.findNext","Eclipse Find Next"),
	ECLIPSE_FINDPREVIOUS("org.eclipse.ui.edit.findPrevious","Eclipse Find Previous"),
	ECLIPSE_FINDREPLACE("org.eclipse.ui.edit.findReplace","Eclipse Find and Replace"),
	ECLIPSE_FINDINCREMENTALREVERSE("org.eclipse.ui.edit.findIncrementalReverse","Eclipse Incremental Find Reverse"),
	ECLIPSE_FINDINCREMENTAL("org.eclipse.ui.edit.findIncremental","Eclipse Incremental Find"),
	ECLIPSE_PASTE("org.eclipse.ui.edit.paste","Eclipse Paste"),
	ECLIPSE_TOGGLE("org.eclipse.quickdiff.toggle","Eclipse Quick Diff Toggle"),
	ECLIPSE_PROPOSALS("org.eclipse.jdt.ui.edit.text.java.correction.assist.proposals","Eclipse Quick Fix"),
	ECLIPSE_REDO("org.eclipse.ui.edit.redo","Eclipse Redo"),
	ECLIPSE_LAST("org.eclipse.jdt.ui.edit.text.java.select.last","Eclipse Restore Last Selection"),
	ECLIPSE_SELECTALL("org.eclipse.ui.edit.selectAll","Eclipse Select All"),
	ECLIPSE_ENCLOSING("org.eclipse.jdt.ui.edit.text.java.select.enclosing","Eclipse Select Enclosing Element"),
	ECLIPSE_NEXT("org.eclipse.jdt.ui.edit.text.java.select.next","Eclipse Select Next Element"),
	ECLIPSE_PREVIOUS("org.eclipse.jdt.ui.edit.text.java.select.previous","Eclipse Select Previous Element"),
	ECLIPSE_TOGGLEBLOCKSELECTIONMODE("org.eclipse.ui.edit.text.toggleBlockSelectionMode","Eclipse Toggle Block Selection"),
	ECLIPSE_TOGGLEINSERTMODE("org.eclipse.ui.edit.text.toggleInsertMode","Eclipse Toggle Insert Mode"),
	ECLIPSE_TOGGLEWORDWRAP("org.eclipse.ui.edit.text.toggleWordWrap","Eclipse Toggle Word Wrap"),
	ECLIPSE_UNDO("org.eclipse.ui.edit.undo","Eclipse Undo"),
	ECLIPSE_HIPPIECOMPLETION("org.eclipse.ui.edit.text.hippieCompletion","Eclipse Word Completion"),
	ECLIPSE_CLOSEALL("org.eclipse.ui.file.closeAll","Eclipse Close All"),
	ECLIPSE_CLOSE("org.eclipse.ui.file.close","Eclipse Close"),
	ECLIPSE_NEWQUICKMENU("org.eclipse.ui.file.newQuickMenu","Eclipse New menu"),
	ECLIPSE_NEWWIZARD("org.eclipse.ui.newWizard","Eclipse New"),
	ECLIPSE_PRINT("org.eclipse.ui.file.print","Eclipse Print"),
	ECLIPSE_PROPERTIES("org.eclipse.ui.file.properties","Eclipse Properties"),
	ECLIPSE_REFRESH("org.eclipse.ui.file.refresh","Eclipse Refresh"),
	ECLIPSE_RENAME("org.eclipse.ui.edit.rename","Eclipse Rename"),
	ECLIPSE_SAVEALL("org.eclipse.ui.file.saveAll","Eclipse Save All"),
	ECLIPSE_SAVE("org.eclipse.ui.file.save","Eclipse Save"),
	ECLIPSE_FORMAT("org.eclipse.pde.ui.edit.text.format","Eclipse Format Source"),
	ECLIPSE_BACKWARDHISTORY("org.eclipse.ui.navigate.backwardHistory","Eclipse Backward History"),
	ECLIPSE_COLLAPSEALL("org.eclipse.ui.navigate.collapseAll","Eclipse Collapse All"),
	ECLIPSE_EXPANDALL("org.eclipse.ui.navigate.expandAll","Eclipse Expand All"),
	ECLIPSE_FORWARDHISTORY("org.eclipse.ui.navigate.forwardHistory","Eclipse Forward History"),
	ECLIPSE_GOTO_LINE("org.eclipse.ui.edit.text.goto.line","Eclipse Go to Line"),
	ECLIPSE_BRACKET("org.eclipse.jdt.ui.edit.text.java.goto.matching.bracket","Eclipse Go to Matching Bracket"),
	ECLIPSE_NXT_MEMBER("org.eclipse.jdt.ui.edit.text.java.goto.next.member","Eclipse Go to Next Member"),
	ECLIPSE_PRV_MEMBER("org.eclipse.jdt.ui.edit.text.java.goto.previous.member","Eclipse Go to Previous Member"),
	ECLIPSE_GOTOLASTEDITPOSITION("org.eclipse.ui.edit.text.gotoLastEditPosition","Eclipse Last Edit Location"),
	ECLIPSE_NEXTPAGE("org.eclipse.ui.part.nextPage","Eclipse Next Page"),
	ECLIPSE_NEXTSUBTAB("org.eclipse.ui.navigate.nextSubTab","Eclipse Next Sub Tab"),
	ECLIPSE_NEXTTAB("org.eclipse.ui.navigate.nextTab","Eclipse Next Tab"),
	ECLIPSE_NAVIGATE_NEXT("org.eclipse.ui.navigate.next","Eclipse Next"),
	ECLIPSE_JAVADOC("org.eclipse.jdt.ui.edit.text.java.open.external.javadoc","Eclipse Open Attached Javadoc"),
	ECLIPSE_CALL_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.call.hierarchy","Eclipse Open Call Hierarchy"),
	ECLIPSE_EDITOR("org.eclipse.jdt.ui.edit.text.java.open.editor","Eclipse Open Declaration"),
	ECLIPSE_OPENMANIFEST("org.eclipse.pde.ui.openManifest","Eclipse Open Manifest"),
	ECLIPSE_OPENPLUGINARTIFACT("org.eclipse.pde.ui.openPluginArtifact","Eclipse Open Plug-in Artifact"),
	ECLIPSE_OPENRESOURCE("org.eclipse.ui.navigate.openResource","Eclipse Open Resource"),
	ECLIPSE_STRUCTURE("org.eclipse.jdt.ui.navigate.java.open.structure","Eclipse Open Structure"),
	ECLIPSE_TYPE_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.type.hierarchy","Eclipse Open Type Hierarchy"),
	ECLIPSE_TYPEIN_HIERARCHY("org.eclipse.jdt.ui.navigate.open.type.in.hierarchy","Eclipse Open Type in Hierarchy"),
	ECLIPSE_TYPE("org.eclipse.jdt.ui.navigate.open.type","Eclipse Open Type"),
	ECLIPSE_OPENFROMCLIPBOARD("org.eclipse.jdt.debug.ui.command.OpenFromClipboard","Eclipse Open from Clipboard"),
	ECLIPSE_PREVIOUSPAGE("org.eclipse.ui.part.previousPage","Eclipse Previous Page"),
	ECLIPSE_PREVIOUSSUBTAB("org.eclipse.ui.navigate.previousSubTab","Eclipse Previous Sub-Tab"),
	ECLIPSE_PREVIOUSTAB("org.eclipse.ui.navigate.previousTab","Eclipse Previous Tab"),
	ECLIPSE_NAVIGATE_PREVIOUS("org.eclipse.ui.navigate.previous","Eclipse Previous"),
	ECLIPSE_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.hierarchy","Eclipse Quick Hierarchy"),
	ECLIPSE_OUTLINE("org.eclipse.jdt.ui.edit.text.java.show.outline","Eclipse Show Outline"),
	ECLIPSE_QUICKOUTLINE("org.eclipse.pde.ui.quickOutline","Eclipse Quick Outline"),
	ECLIPSE_GOTOBREADCRUMB("org.eclipse.jdt.ui.edit.text.java.gotoBreadcrumb","Eclipse Show In Breadcrumb"),
	ECLIPSE_SHOWINQUICKMENU("org.eclipse.ui.navigate.showInQuickMenu","Eclipse Show In Quick Menu"),
	ECLIPSE_BUILDALL("org.eclipse.ui.project.buildAll","Eclipse Build All"),
	ECLIPSE_PARAMETERS("org.eclipse.jdt.ui.edit.text.java.modify.method.parameters","Eclipse Change Method Signature"),
	ECLIPSE_VARIABLE("org.eclipse.jdt.ui.edit.text.java.extract.local.variable","Eclipse Extract Local Variable"),
	ECLIPSE_METHOD("org.eclipse.jdt.ui.edit.text.java.extract.method","Eclipse Extract Method"),
	ECLIPSE_INLINE("org.eclipse.jdt.ui.edit.text.java.inline","Eclipse Inline"),
	ECLIPSE_MOVE_ELEMENT("org.eclipse.jdt.ui.edit.text.java.move.element","Eclipse Move"),
	ECLIPSE_RENAME_ELEMENT("org.eclipse.jdt.ui.edit.text.java.rename.element","Eclipse Rename"),
	ECLIPSE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.refactor.quickMenu","Eclipse Show Refactor Quick Menu"),
	ECLIPSE_ADDMEMORYMONITOR("org.eclipse.debug.ui.commands.addMemoryMonitor","Eclipse Add Memory Block"),
	ECLIPSE_ALLINSTANCES("org.eclipse.jdt.debug.ui.commands.AllInstances","Eclipse All Instances"),
	ECLIPSE_CLOSERENDERING("org.eclipse.debug.ui.commands.closeRendering","Eclipse Close Rendering"),
	ECLIPSE_DEBUG_1("org.eclipse.ant.ui.antShortcut.debug","Eclipse Debug Ant Build"),
	ECLIPSE_DEBUG_2("org.eclipse.pde.ui.runtimeWorkbenchShortcut.debug","Eclipse Debug Eclipse Application"),
	ECLIPSE_DEBUG_3("org.eclipse.pde.ui.junitWorkbenchShortcut.debug","Eclipse Debug JUnit Plug-in Test"),
	ECLIPSE_DEBUG_4("org.eclipse.jdt.junit.junitShortcut.debug","Eclipse Debug JUnit Test"),
	ECLIPSE_DEBUG_5("org.eclipse.jdt.debug.ui.javaAppletShortcut.debug","Eclipse Debug Java Applet"),
	ECLIPSE_DEBUG_6("org.eclipse.jdt.debug.ui.localJavaShortcut.debug","Eclipse Debug Java Application"),
	ECLIPSE_DEBUG_7("org.eclipse.pde.ui.EquinoxLaunchShortcut.debug","Eclipse Debug OSGi Framework"),
	ECLIPSE_DEBUGLAST("org.eclipse.debug.ui.commands.DebugLast","Eclipse Debug"),
	ECLIPSE_DISPLAY("org.eclipse.jdt.debug.ui.commands.Display","Eclipse Display"),
	ECLIPSE_EOF("org.eclipse.debug.ui.commands.eof","Eclipse End Off File"),
	ECLIPSE_EXECUTE("org.eclipse.jdt.debug.ui.commands.Execute","Eclipse Execute"),
	ECLIPSE_FORCERETURN("org.eclipse.jdt.debug.ui.commands.ForceReturn","Eclipse Force Return"),
	ECLIPSE_GOTOADDRESS("org.eclipse.debug.ui.command.gotoaddress","Eclipse Go to Address"),
	ECLIPSE_INSPECT("org.eclipse.jdt.debug.ui.commands.Inspect","Eclipse Inspect"),
	ECLIPSE_BREAKPOINT_PROPERTIES("org.eclipse.jdt.debug.ui.breakpoint.properties","Eclipse Java Breakpoint Properties"),
	ECLIPSE_NEWRENDERING("org.eclipse.debug.ui.commands.newRendering","Eclipse New Rendering"),
	ECLIPSE_NEXTMEMORYBLOCK("org.eclipse.debug.ui.commands.nextMemoryBlock","Eclipse Next Memory Monitor"),
	ECLIPSE_MEMORY_NEXTPAGE("org.eclipse.debug.ui.command.nextpage","Eclipse Next Page of Memory"),
	ECLIPSE_PREVPAGE("org.eclipse.debug.ui.command.prevpage","Eclipse Previous Page of Memory"),
	ECLIPSE_RESUME("org.eclipse.debug.ui.commands.Resume","Eclipse Resume"),
	ECLIPSE_RUN_1("org.eclipse.ant.ui.antShortcut.run","Eclipse Run Ant Build"),
	ECLIPSE_RUN_2("org.eclipse.pde.ui.runtimeWorkbenchShortcut.run","Eclipse Run Eclipse Application"),
	ECLIPSE_RUN_3("org.eclipse.pde.ui.junitWorkbenchShortcut.run","Eclipse Run JUnit Plug-in Test"),
	ECLIPSE_RUN_4("org.eclipse.jdt.junit.junitShortcut.run","Eclipse Run JUnit Test"),
	ECLIPSE_RUN_5("org.eclipse.jdt.debug.ui.javaAppletShortcut.run","Eclipse Run Java Applet"),
	ECLIPSE_RUN_6("org.eclipse.jdt.debug.ui.localJavaShortcut.run","Eclipse Run Java Application"),
	ECLIPSE_RUN_7("org.eclipse.pde.ui.EquinoxLaunchShortcut.run","Eclipse Run OSGi Framework"),
	ECLIPSE_RUNTOLINE("org.eclipse.debug.ui.commands.RunToLine","Eclipse Run to Line"),
	ECLIPSE_RUNLAST("org.eclipse.debug.ui.commands.RunLast","Eclipse Run"),
	ECLIPSE_SKIPALLBREAKPOINTS("org.eclipse.debug.ui.commands.SkipAllBreakpoints","Eclipse Skip All Breakpoints"),
	ECLIPSE_STEPINTOSELECTION("org.eclipse.jdt.debug.ui.commands.StepIntoSelection","Eclipse Step Into Selection"),
	ECLIPSE_STEPINTO("org.eclipse.debug.ui.commands.StepInto","Eclipse Step Into"),
	ECLIPSE_STEPOVER("org.eclipse.debug.ui.commands.StepOver","Eclipse Step Over"),
	ECLIPSE_STEPRETURN("org.eclipse.debug.ui.commands.StepReturn","Eclipse Step Return"),
	ECLIPSE_TERMINATE("org.eclipse.debug.ui.commands.Terminate","Eclipse Terminate"),
	ECLIPSE_TOGGLEBREAKPOINT("org.eclipse.debug.ui.commands.ToggleBreakpoint","Eclipse Toggle Breakpoint"),
	ECLIPSE_TOGGLEMEMORYMONITORSPANE("org.eclipse.debug.ui.commands.toggleMemoryMonitorsPane","Eclipse Toggle Memory Monitors Pane"),
	ECLIPSE_TOGGLESTEPFILTERS("org.eclipse.debug.ui.commands.ToggleStepFilters","Eclipse Use Step Filters"),
	ECLIPSE_DECLARATIONS_WORKSPACE("org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace","Eclipse Declaration in Workspace"),
	ECLIPSE_PERFORMTEXTSEARCHWORKSPACE("org.eclipse.search.ui.performTextSearchWorkspace","Eclipse Find Text in Workspace"),
	ECLIPSE_OPENSEARCHDIALOG("org.eclipse.search.ui.openSearchDialog","Eclipse Open Search Dialog"),
	ECLIPSE_REFERENCES_WORKSPACE("org.eclipse.jdt.ui.edit.text.java.search.references.in.workspace","Eclipse References in Workspace"),
	ECLIPSE_FILE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.search.occurrences.in.file.quickMenu","Eclipse Show Occurrences in File Quick Menu"),
	ECLIPSE_COMMENT("org.eclipse.jdt.ui.edit.text.java.add.block.comment","Eclipse Add Block Comment"),
	ECLIPSE_IMPORT("org.eclipse.jdt.ui.edit.text.java.add.import","Eclipse Add Import"),
	ECLIPSE_JAVADOC_COMMENT("org.eclipse.jdt.ui.edit.text.java.add.javadoc.comment","Eclipse Add Javadoc Comment"),
	ECLIPSE_CLASSFILE("org.eclipse.jdt.ui.edit.text.java.annotate.classFile","Eclipse Annotate Class File"),
	ECLIPSE_INDENT("org.eclipse.jdt.ui.edit.text.java.indent","Eclipse Correct Indentation"),
	ECLIPSE_JAVA_FORMAT("org.eclipse.jdt.ui.edit.text.java.format","Eclipse Format"),
	ECLIPSE_COMMAND("org.eclipse.ant.ui.open.declaration.command","Eclipse Open Declaration"),
	ECLIPSE_OPENEXTERNALDOC("org.eclipse.ant.ui.openExternalDoc","Eclipse Open External Documentation"),
	ECLIPSE_IMPORTS("org.eclipse.jdt.ui.edit.text.java.organize.imports","Eclipse Organize Imports"),
	ECLIPSE_ASSIST_1("org.eclipse.jdt.ui.correction.assignToField.assist","Eclipse Assign to field"),
	ECLIPSE_ASSIST_2("org.eclipse.jdt.ui.correction.assignToLocal.assist","Eclipse Assign to local variable"),
	ECLIPSE_ASSIST_3("org.eclipse.jdt.ui.correction.extractMethodInplace.assist","Eclipse Extract method"),
	ECLIPSE_ASSIST_4("org.eclipse.jdt.ui.correction.renameInFile.assist","Eclipse Rename in file"),
	ECLIPSE_BLOCK_COMMENT("org.eclipse.jdt.ui.edit.text.java.remove.block.comment","Eclipse Remove Block Comment"),
	ECLIPSE_ANNOTATIONS("org.eclipse.jdt.ui.edit.text.remove.occurrence.annotations","Eclipse Remove Occurrence Annotations"),
	ECLIPSE_RENAMEINFILE("org.eclipse.ant.ui.renameInFile","Eclipse Rename In File"),
	ECLIPSE_SOURCE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.source.quickMenu","Eclipse Show Source Quick Menu"),
	ECLIPSE_SURROUND_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.surround.with.quickMenu","Eclipse Surround With Quick Menu"),
	ECLIPSE_ANT_TOGGLEMARKOCCURRENCES("org.eclipse.ant.ui.toggleMarkOccurrences","Eclipse Toggle Ant Mark Occurrences"),
	ECLIPSE_TOGGLE_COMMENT("org.eclipse.jdt.ui.edit.text.java.toggle.comment","Eclipse Toggle Comment"),
	ECLIPSE_JAVA_TOGGLEMARKOCCURRENCES("org.eclipse.jdt.ui.edit.text.java.toggleMarkOccurrences","Eclipse Toggle Mark Occurrences"),
	ECLIPSE_LAYOUTSPYCOMMAND("org.eclipse.tools.layout.spy.commands.layoutSpyCommand","Eclipse Layout Spy"),
	ECLIPSE_MENUSPYCOMMAND("org.eclipse.pde.runtime.spy.commands.menuSpyCommand","Eclipse Plug-in Menu Spy"),
	ECLIPSE_SPYCOMMAND("org.eclipse.pde.runtime.spy.commands.spyCommand","Eclipse Plug-in Selection Spy"),
	ECLIPSE_COLLAPSE_ALL("org.eclipse.ui.edit.text.folding.collapse_all","Eclipse Collapse All"),
	ECLIPSE_COLLAPSE("org.eclipse.ui.edit.text.folding.collapse","Eclipse Collapse"),
	ECLIPSE_COPYLINEDOWN("org.eclipse.ui.edit.text.copyLineDown","Eclipse Copy Lines"),
	ECLIPSE_DELETE_LINE("org.eclipse.ui.edit.text.delete.line","Eclipse Delete Line"),
	ECLIPSE_DELETENEXTWORD("org.eclipse.ui.edit.text.deleteNextWord","Eclipse Delete Next Word"),
	ECLIPSE_DELETEPREVIOUSWORD("org.eclipse.ui.edit.text.deletePreviousWord","Eclipse Delete Previous Word"),
	ECLIPSE_END("org.eclipse.ui.edit.text.delete.line.to.end","Eclipse Delete to End of Line"),
	ECLIPSE_COPYLINEUP("org.eclipse.ui.edit.text.copyLineUp","Eclipse Duplicate Lines"),
	ECLIPSE_EXPAND_ALL("org.eclipse.ui.edit.text.folding.expand_all","Eclipse Expand All"),
	ECLIPSE_EXPAND("org.eclipse.ui.edit.text.folding.expand","Eclipse Expand"),
	ECLIPSE_SMARTENTERINVERSE("org.eclipse.ui.edit.text.smartEnterInverse","Eclipse Insert Line Above Current Line"),
	ECLIPSE_SMARTENTER("org.eclipse.ui.edit.text.smartEnter","Eclipse Insert Line Below Current Line"),
	ECLIPSE_LINES("org.eclipse.ui.edit.text.join.lines","Eclipse Join Lines"),
	ECLIPSE_GOTO_LINEEND("org.eclipse.ui.edit.text.goto.lineEnd","Eclipse Line End"),
	ECLIPSE_GOTO_LINESTART("org.eclipse.ui.edit.text.goto.lineStart","Eclipse Line Start"),
	ECLIPSE_MOVELINEDOWN("org.eclipse.ui.edit.text.moveLineDown","Eclipse Move Lines Down"),
	ECLIPSE_MOVELINEUP("org.eclipse.ui.edit.text.moveLineUp","Eclipse Move Lines Up"),
	ECLIPSE_GOTO_WORDNEXT("org.eclipse.ui.edit.text.goto.wordNext","Eclipse Next Word"),
	ECLIPSE_HYPERLINK("org.eclipse.ui.edit.text.open.hyperlink","Eclipse Open Hyperlink"),
	ECLIPSE_GOTO_WORDPREVIOUS("org.eclipse.ui.edit.text.goto.wordPrevious","Eclipse Previous Word"),
	ECLIPSE_RESTORE("org.eclipse.ui.edit.text.folding.restore","Eclipse Reset Structure"),
	ECLIPSE_LINEDOWN("org.eclipse.ui.edit.text.scroll.lineDown","Eclipse Scroll Line Down"),
	ECLIPSE_LINEUP("org.eclipse.ui.edit.text.scroll.lineUp","Eclipse Scroll Line Up"),
	ECLIPSE_SELECT_LINEEND("org.eclipse.ui.edit.text.select.lineEnd","Eclipse Select Line End"),
	ECLIPSE_SELECT_LINESTART("org.eclipse.ui.edit.text.select.lineStart","Eclipse Select Line Start"),
	ECLIPSE_SELECT_WORDNEXT("org.eclipse.ui.edit.text.select.wordNext","Eclipse Select Next Word"),
	ECLIPSE_SELECT_WORDPREVIOUS("org.eclipse.ui.edit.text.select.wordPrevious","Eclipse Select Previous Word"),
	ECLIPSE_SHOWINFORMATION("org.eclipse.ui.edit.text.showInformation","Eclipse Show Tooltip Description"),
	ECLIPSE_TEXTEND("org.eclipse.ui.edit.text.goto.textEnd","Eclipse Text End"),
	ECLIPSE_TEXTSTART("org.eclipse.ui.edit.text.goto.textStart","Eclipse Text Start"),
	ECLIPSE_LOWERCASE("org.eclipse.ui.edit.text.lowerCase","Eclipse To Lower Case"),
	ECLIPSE_UPPERCASE("org.eclipse.ui.edit.text.upperCase","Eclipse To Upper Case"),
	ECLIPSE_TOGGLE_FOLDING("org.eclipse.ui.edit.text.folding.toggle","Eclipse Toggle Folding"),
	ECLIPSE_TOGGLEOVERWRITE("org.eclipse.ui.edit.text.toggleOverwrite","Eclipse Toggle Overwrite"),
	ECLIPSE_ZOOMIN("org.eclipse.ui.edit.text.zoomIn","Eclipse Zoom In"),
	ECLIPSE_ZOOMOUT("org.eclipse.ui.edit.text.zoomOut","Eclipse Zoom Out"),
	ECLIPSE_SEARCHTARGETREPOSITORIES("org.eclipse.pde.ui.searchTargetRepositories","Eclipse Add Artifact to Target Platform"),
	ECLIPSE_FINDREFERENCES("org.eclipse.ui.genericeditor.findReferences","Eclipse Find References"),
	ECLIPSE_SHOWVIEW("org.eclipse.ui.views.showView","Eclipse Show View"),
	ECLIPSE_ACTIVATEEDITOR("org.eclipse.ui.window.activateEditor","Eclipse Activate Editor"),
	ECLIPSE_NEXTEDITOR("org.eclipse.ui.window.nextEditor","Eclipse Next Editor"),
	ECLIPSE_NEXTPERSPECTIVE("org.eclipse.ui.window.nextPerspective","Eclipse Next Perspective"),
	ECLIPSE_NEXTVIEW("org.eclipse.ui.window.nextView","Eclipse Next View"),
	ECLIPSE_PREVIOUSEDITOR("org.eclipse.ui.window.previousEditor","Eclipse Previous Editor"),
	ECLIPSE_PREVIOUSPERSPECTIVE("org.eclipse.ui.window.previousPerspective","Eclipse Previous Perspective"),
	ECLIPSE_PREVIOUSVIEW("org.eclipse.ui.window.previousView","Eclipse Previous View"),
	ECLIPSE_QUICKACCESS("org.eclipse.ui.window.quickAccess","Eclipse Quick Access"),
	ECLIPSE_OPENEDITORDROPDOWN("org.eclipse.ui.window.openEditorDropDown","Eclipse Quick Switch Editor"),
	ECLIPSE_SPY("org.eclipse.ui.window.spy","Eclipse Show Contributing Plug-in"),
	ECLIPSE_SHOWKEYASSIST("org.eclipse.ui.window.showKeyAssist","Eclipse Show Key Assist"),
	ECLIPSE_SHOWRULERCONTEXTMENU("org.eclipse.ui.edit.text.showRulerContextMenu","Eclipse Show Ruler Context Menu"),
	ECLIPSE_SHOWSYSTEMMENU("org.eclipse.ui.window.showSystemMenu","Eclipse Show System Menu"),
	ECLIPSE_SHOWVIEWMENU("org.eclipse.ui.window.showViewMenu","Eclipse Show View Menu"),
	ECLIPSE_SWITCHTOEDITOR("org.eclipse.ui.window.switchToEditor","Eclipse Switch to Editor"),
	ECLIPSE_FULLSCREENMODE("org.eclipse.ui.window.fullscreenmode","Eclipse Toggle Full Screen"),
	ECLIPSE_SPLITEDITOR("org.eclipse.ui.window.splitEditor","Eclipse Toggle Split Editor"),
	ECLIPSE_TASK("org.eclipse.mylyn.tasks.ui.command.openTask","Eclipse Open Task"),
	ECLIPSE_GET_SET("org.eclipse.jdt.ui.edit.text.java.create.getter.setter","Eclipse Insert Get Set"),
	ECLIPSE_HASH_EQUALS("org.eclipse.jdt.ui.edit.text.java.generate.hashcode.equals","Eclipse Insert Hash"),
	ECLIPSE_TO_STRING("org.eclipse.jdt.ui.edit.text.java.generate.tostring","Eclipse Insert String"),
	ECLIPSE_CONSTRUCTOR("org.eclipse.jdt.ui.edit.text.java.generate.constructor.using.fields","Eclipse Insert Constructor"),
	ECLIPSE_ACTION_TERMINATE("org.eclipse.debug.ui.actions.Terminate","Eclipse Action Terminate"),
	ECLIPSE_ACTION_RESUME("org.eclipse.debug.ui.actions.Resume","Eclipse Action Resume"),
	ECLIPSE_REBUILD("org.eclipse.jdt.ui.index.rebuild","Eclipse Rebuild"),
	ECLIPSE_FILE_CLOSE_OTHERS("org.eclipse.ui.file.closeOthers","Eclipse Close Others"),
	ECLIPSE_OPEN_WORKSPACE("org.eclipse.ui.file.openWorkspace","Eclipse Open Workspace"),
	ECLIPSE_STOP_PLUGIN("stop plugin","Eclipse Stop Listening"),
	ECLIPSE_FILE_IMPORT("org.eclipse.ui.file.import","Eclipse Import"),
	ECLIPSE_FILE_EXPORT("org.eclipse.ui.file.export","Eclipse Export"),
	ECLIPSE_FILE_SAVE_AS("org.eclipse.ui.file.saveAs","Eclipse Save As"),
	ECLIPSE_FILE_REVERT("org.eclipse.ui.file.revert","Eclipse Revert"),
	ECLIPSE_FILE_RESTART("org.eclipse.ui.file.restartWorkbench","Eclipse Restart Workbench"),
	ECLIPSE_FILE_PROPERTIES("org.eclipse.ui.file.properties","Eclipse File Properties"),
	ECLIPSE_FILE_EXIT("org.eclipse.ui.file.exit","Eclipse File Exit"),
	ECLIPSE_FILE_MOVE("org.eclipse.ui.edit.move","Eclipse File Move"),
	ECLIPSE_CONTENT_ASSIST("org.eclipse.ui.edit.text.contentAssist.proposals","Eclipse Content Assist"),
	ECLIPSE_ADD_TASK("org.eclipse.ui.edit.addTask","Eclipse Add Task"),
	ECLIPSE_ADD_BOOKMARK("org.eclipse.ui.edit.addBookmark","Eclipse Add Bookmark"),
	ECLIPSE_NAVIGATE_GO_INTO("org.eclipse.ui.navigate.goInto","Eclipse Go Into"),
	ECLIPSE_NAVIGATE_BACK("org.eclipse.ui.navigate.back","Eclipse Navigate Back"),
	ECLIPSE_NAVIGATE_FORWARD("org.eclipse.ui.navigate.forward","Eclipse Navigate Forward"),
	ECLIPSE_NAVIGATE_UP("org.eclipse.ui.navigate.up","Eclipse Up"),
	ECLIPSE_NAVIGATE_LINK_WITH_EDITOR("org.eclipse.ui.navigate.linkWithEditor","Eclipse Link With Editor"),
	ECLIPSE_NAVIGATE_SHOW_IN("org.eclipse.ui.navigate.showIn","Eclipse Show In"),
	ECLIPSE_NAVIGATE_SHOW_IN_TARGET("org.eclipse.ui.navigate.showIn.targetId","Eclipse Show In Target"),
	ECLIPSE_BUILD_PROJECT("org.eclipse.ui.project.buildProject","Eclipse Build Project"),
	ECLIPSE_CLOSE_PROJECT("org.eclipse.ui.project.closeProject","Eclipse Close Project"),
	ECLIPSE_CLOSE_UNRELATED_PROJECTS("org.eclipse.ui.project.closeUnrelatedProjects","Eclipse Close Unrelated Projects"),
	ECLIPSE_PROJECT_OPEN_PROJECT("org.eclipse.ui.project.openProject","Eclipse Open Project"),
	ECLIPSE_WINDOW_NEW_WINDOW("org.eclipse.ui.window.newWindow","Eclipse New Window"),
	ECLIPSE_WINDOW_NEW_EDITOR("org.eclipse.ui.window.newEditor","Eclipse New Editor"),
	ECLIPSE_WINDOW_MAXIMIZE_EDITOR("org.eclipse.ui.window.maximizePart","Eclipse Maximize Active View"),
	ECLIPSE_WINDOW_MINIMIZE_EDITOR("org.eclipse.ui.window.minimizePart","Eclipse Minimize Active View"),
	ECLIPSE_WINDOW_CLOSE_ALL_PERSPECTIVES("org.eclipse.ui.window.closeAllPerspectives","Eclipse Close All Perspectives"),
	ECLIPSE_WINDOW_CLOSE_PERSPECTIVE("org.eclipse.ui.window.closePerspective","Eclipse Close Perspective"),
	ECLIPSE_WINDOW_CLOSE_PERSPECTIVE_ID("org.eclipse.ui.window.closePerspective.perspectiveId","Eclipse Close Perspective id"),
	ECLIPSE_WINDOW_CLOSE_PART("org.eclipse.ui.file.closePart","Eclipse Close Part"),
	ECLIPSE_WINDOW_CUSTOMIZE_PERSPECTIVE("org.eclipse.ui.window.customizePerspective","Eclipse Customize Perspective"),
	ECLIPSE_WINDOW_PIN_EDITOR("org.eclipse.ui.window.pinEditor","Eclipse Pin Editor"),
	ECLIPSE_WINDOW_PREFERENCES("org.eclipse.ui.window.preferences","Eclipse Preferences"),
	ECLIPSE_WINDOW_RESET_PERSPECTIVE("org.eclipse.ui.window.resetPerspective","Eclipse Reset Perspective"),
	ECLIPSE_WINDOW_SAVE_PERSPECTIVE("org.eclipse.ui.window.savePerspective","Eclipse Save Perspective"),
	ECLIPSE_WINDOW_LOCK_TOOLBAR("org.eclipse.ui.window.lockToolBar","Eclipse Lock Toolbar"),
	ECLIPSE_HELP_CONTENTS("org.eclipse.ui.help.helpContents","Eclipse Help Contents"),
	ECLIPSE_HELP_SEARCH("org.eclipse.ui.help.helpSearch","Eclipse Help Search"),
	ECLIPSE_DYNAMIC_HELP("org.eclipse.ui.help.dynamicHelp","Eclipse Dynamic Help"),
	ECLIPSE_HELP_WELCOME("org.eclipse.ui.help.quickStartAction","Eclipse Help Welcome"),
	ECLIPSE_HELP_TIPS_AND_TRICKS("org.eclipse.ui.help.tipsAndTricksAction","Eclipse Help Tips And Tricks"),
	ECLIPSE_HELP_ABOUT("org.eclipse.ui.help.aboutAction","Eclipse Help About"),
	ECLIPSE_SHOW_PERSPECTIVE("org.eclipse.ui.perspectives.showPerspective","Eclipse Show Perspective"),
	ECLIPSE_SCROLL_DOWN("org.eclipse.ui.edit.text.scroll.lineDown","Eclipse Scroll Down");
  
  private String eclipseId;
  private String actionId;
  
  private Action(String eclipseId, String actionId)
  {
    this.eclipseId = eclipseId;
    this.actionId = actionId;
  }
  
  public String getEclipseId()
  {
    return this.eclipseId;
  }
  
  public String getActionId()
  {
    return this.actionId;
  }
  
  public String formatCommand()
  {
    StringBuilder sb = new StringBuilder();
    sb.append(name());
    sb.append(": ");
    sb.append(this.eclipseId);
    return sb.toString();
  }
  
  public String toString()
  {
    return formatCommand();
  }
}