package voxpopuli.action;

public enum Action {
	ECLIPSE_CONTEXTINFORMATION("org.eclipse.ui.edit.text.contentAssist.contextInformation", "Vox Context Information"),
	ECLIPSE_COPY("org.eclipse.ui.edit.copy", "Vox Copy"), ECLIPSE_CUT("org.eclipse.ui.edit.cut", "Vox Cut"),
	ECLIPSE_DELETE("org.eclipse.ui.edit.delete", "Vox Delete"),
	ECLIPSE_FINDNEXT("org.eclipse.ui.edit.findNext", "Vox Find Next"),
	ECLIPSE_FINDPREVIOUS("org.eclipse.ui.edit.findPrevious", "Vox Find Previous"),
	ECLIPSE_FINDREPLACE("org.eclipse.ui.edit.findReplace", "Vox Find and Replace"),
	ECLIPSE_FINDINCREMENTALREVERSE("org.eclipse.ui.edit.findIncrementalReverse", "Vox Incremental Find Reverse"),
	ECLIPSE_FINDINCREMENTAL("org.eclipse.ui.edit.findIncremental", "Vox Incremental Find"),
	ECLIPSE_PASTE("org.eclipse.ui.edit.paste", "Vox Paste"),
	ECLIPSE_TOGGLE("org.eclipse.quickdiff.toggle", "Vox Quick Diff Toggle"),
	ECLIPSE_PROPOSALS("org.eclipse.jdt.ui.edit.text.java.correction.assist.proposals", "Vox Quick Fix"),
	ECLIPSE_REDO("org.eclipse.ui.edit.redo", "Vox Redo"),
	ECLIPSE_LAST("org.eclipse.jdt.ui.edit.text.java.select.last", "Vox Restore Last Selection"),
	ECLIPSE_SELECTALL("org.eclipse.ui.edit.selectAll", "Vox Select All"),
	ECLIPSE_ENCLOSING("org.eclipse.jdt.ui.edit.text.java.select.enclosing", "Vox Select Enclosing Element"),
	ECLIPSE_NEXT("org.eclipse.jdt.ui.edit.text.java.select.next", "Vox Select Next Element"),
	ECLIPSE_PREVIOUS("org.eclipse.jdt.ui.edit.text.java.select.previous", "Vox Select Previous Element"),
	ECLIPSE_TOGGLEBLOCKSELECTIONMODE("org.eclipse.ui.edit.text.toggleBlockSelectionMode", "Vox Toggle Block Selection"),
	ECLIPSE_TOGGLEINSERTMODE("org.eclipse.ui.edit.text.toggleInsertMode", "Vox Toggle Insert Mode"),
	ECLIPSE_TOGGLEWORDWRAP("org.eclipse.ui.edit.text.toggleWordWrap", "Vox Toggle Word Wrap"),
	ECLIPSE_UNDO("org.eclipse.ui.edit.undo", "Vox Undo"),
	ECLIPSE_HIPPIECOMPLETION("org.eclipse.ui.edit.text.hippieCompletion", "Vox Word Completion"),
	ECLIPSE_CLOSEALL("org.eclipse.ui.file.closeAll", "Vox Close All"),
	ECLIPSE_CLOSE("org.eclipse.ui.file.close", "Vox Close"),
	ECLIPSE_NEWQUICKMENU("org.eclipse.ui.file.newQuickMenu", "Vox New menu"),
	ECLIPSE_NEWWIZARD("org.eclipse.ui.newWizard", "Vox New"), ECLIPSE_PRINT("org.eclipse.ui.file.print", "Vox Print"),
	ECLIPSE_PROPERTIES("org.eclipse.ui.file.properties", "Vox Properties"),
	ECLIPSE_REFRESH("org.eclipse.ui.file.refresh", "Vox Refresh"),
	ECLIPSE_RENAME("org.eclipse.ui.edit.rename", "Vox Rename"),
	ECLIPSE_SAVEALL("org.eclipse.ui.file.saveAll", "Vox Save All"),
	ECLIPSE_SAVE("org.eclipse.ui.file.save", "Vox Save"),
	ECLIPSE_FORMAT("org.eclipse.pde.ui.edit.text.format", "Vox Format Source"),
	ECLIPSE_BACKWARDHISTORY("org.eclipse.ui.navigate.backwardHistory", "Vox Backward History"),
	ECLIPSE_COLLAPSEALL("org.eclipse.ui.navigate.collapseAll", "Vox Collapse All"),
	ECLIPSE_EXPANDALL("org.eclipse.ui.navigate.expandAll", "Vox Expand All"),
	ECLIPSE_FORWARDHISTORY("org.eclipse.ui.navigate.forwardHistory", "Vox Forward History"),
	ECLIPSE_GOTO_LINE("org.eclipse.ui.edit.text.goto.line", "Vox Go to Line"),
	ECLIPSE_BRACKET("org.eclipse.jdt.ui.edit.text.java.goto.matching.bracket", "Vox Go to Matching Bracket"),
	ECLIPSE_NXT_MEMBER("org.eclipse.jdt.ui.edit.text.java.goto.next.member", "Vox Go to Next Member"),
	ECLIPSE_PRV_MEMBER("org.eclipse.jdt.ui.edit.text.java.goto.previous.member", "Vox Go to Previous Member"),
	ECLIPSE_GOTOLASTEDITPOSITION("org.eclipse.ui.edit.text.gotoLastEditPosition", "Vox Last Edit Location"),
	ECLIPSE_NEXTPAGE("org.eclipse.ui.part.nextPage", "Vox Next Page"),
	ECLIPSE_NEXTSUBTAB("org.eclipse.ui.navigate.nextSubTab", "Vox Next Sub Tab"),
	ECLIPSE_NEXTTAB("org.eclipse.ui.navigate.nextTab", "Vox Next Tab"),
	ECLIPSE_NAVIGATE_NEXT("org.eclipse.ui.navigate.next", "Vox Next"),
	ECLIPSE_JAVADOC("org.eclipse.jdt.ui.edit.text.java.open.external.javadoc", "Vox Open Attached Javadoc"),
	ECLIPSE_CALL_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.call.hierarchy", "Vox Open Call Hierarchy"),
	ECLIPSE_EDITOR("org.eclipse.jdt.ui.edit.text.java.open.editor", "Vox Open Declaration"),
	ECLIPSE_OPENMANIFEST("org.eclipse.pde.ui.openManifest", "Vox Open Manifest"),
	ECLIPSE_OPENPLUGINARTIFACT("org.eclipse.pde.ui.openPluginArtifact", "Vox Open Plug-in Artifact"),
	ECLIPSE_OPENRESOURCE("org.eclipse.ui.navigate.openResource", "Vox Open Resource"),
	ECLIPSE_STRUCTURE("org.eclipse.jdt.ui.navigate.java.open.structure", "Vox Open Structure"),
	ECLIPSE_TYPE_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.type.hierarchy", "Vox Open Type Hierarchy"),
	ECLIPSE_TYPEIN_HIERARCHY("org.eclipse.jdt.ui.navigate.open.type.in.hierarchy", "Vox Open Type in Hierarchy"),
	ECLIPSE_TYPE("org.eclipse.jdt.ui.navigate.open.type", "Vox Open Type"),
	ECLIPSE_OPENFROMCLIPBOARD("org.eclipse.jdt.debug.ui.command.OpenFromClipboard", "Vox Open from Clipboard"),
	ECLIPSE_PREVIOUSPAGE("org.eclipse.ui.part.previousPage", "Vox Previous Page"),
	ECLIPSE_PREVIOUSSUBTAB("org.eclipse.ui.navigate.previousSubTab", "Vox Previous Sub-Tab"),
	ECLIPSE_PREVIOUSTAB("org.eclipse.ui.navigate.previousTab", "Vox Previous Tab"),
	ECLIPSE_NAVIGATE_PREVIOUS("org.eclipse.ui.navigate.previous", "Vox Previous"),
	ECLIPSE_HIERARCHY("org.eclipse.jdt.ui.edit.text.java.open.hierarchy", "Vox Quick Hierarchy"),
	ECLIPSE_OUTLINE("org.eclipse.jdt.ui.edit.text.java.show.outline", "Vox Show Outline"),
	ECLIPSE_QUICKOUTLINE("org.eclipse.pde.ui.quickOutline", "Vox Quick Outline"),
	ECLIPSE_GOTOBREADCRUMB("org.eclipse.jdt.ui.edit.text.java.gotoBreadcrumb", "Vox Show In Breadcrumb"),
	ECLIPSE_SHOWINQUICKMENU("org.eclipse.ui.navigate.showInQuickMenu", "Vox Show In Quick Menu"),
	ECLIPSE_BUILDALL("org.eclipse.ui.project.buildAll", "Vox Build All"),
	ECLIPSE_PARAMETERS("org.eclipse.jdt.ui.edit.text.java.modify.method.parameters", "Vox Change Method Signature"),
	ECLIPSE_VARIABLE("org.eclipse.jdt.ui.edit.text.java.extract.local.variable", "Vox Extract Local Variable"),
	ECLIPSE_METHOD("org.eclipse.jdt.ui.edit.text.java.extract.method", "Vox Extract Method"),
	ECLIPSE_INLINE("org.eclipse.jdt.ui.edit.text.java.inline", "Vox Inline"),
	ECLIPSE_MOVE_ELEMENT("org.eclipse.jdt.ui.edit.text.java.move.element", "Vox Move"),
	ECLIPSE_RENAME_ELEMENT("org.eclipse.jdt.ui.edit.text.java.rename.element", "Vox Rename"),
	ECLIPSE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.refactor.quickMenu", "Vox Show Refactor Quick Menu"),
	ECLIPSE_ADDMEMORYMONITOR("org.eclipse.debug.ui.commands.addMemoryMonitor", "Vox Add Memory Block"),
	ECLIPSE_ALLINSTANCES("org.eclipse.jdt.debug.ui.commands.AllInstances", "Vox All Instances"),
	ECLIPSE_CLOSERENDERING("org.eclipse.debug.ui.commands.closeRendering", "Vox Close Rendering"),
	ECLIPSE_DEBUG_1("org.eclipse.ant.ui.antShortcut.debug", "Vox Debug Ant Build"),
	ECLIPSE_DEBUG_2("org.eclipse.pde.ui.runtimeWorkbenchShortcut.debug", "Vox Debug Eclipse Application"),
	ECLIPSE_DEBUG_3("org.eclipse.pde.ui.junitWorkbenchShortcut.debug", "Vox Debug JUnit Plug-in Test"),
	ECLIPSE_DEBUG_4("org.eclipse.jdt.junit.junitShortcut.debug", "Vox Debug JUnit Test"),
	ECLIPSE_DEBUG_5("org.eclipse.jdt.debug.ui.javaAppletShortcut.debug", "Vox Debug Java Applet"),
	ECLIPSE_DEBUG_6("org.eclipse.jdt.debug.ui.localJavaShortcut.debug", "Vox Debug Java Application"),
	ECLIPSE_DEBUG_7("org.eclipse.pde.ui.EquinoxLaunchShortcut.debug", "Vox Debug OSGi Framework"),
	ECLIPSE_DEBUGLAST("org.eclipse.debug.ui.commands.DebugLast", "Vox Debug"),
	ECLIPSE_DISPLAY("org.eclipse.jdt.debug.ui.commands.Display", "Vox Display"),
	ECLIPSE_EOF("org.eclipse.debug.ui.commands.eof", "Vox End Off File"),
	ECLIPSE_EXECUTE("org.eclipse.jdt.debug.ui.commands.Execute", "Vox Execute"),
	ECLIPSE_FORCERETURN("org.eclipse.jdt.debug.ui.commands.ForceReturn", "Vox Force Return"),
	ECLIPSE_GOTOADDRESS("org.eclipse.debug.ui.command.gotoaddress", "Vox Go to Address"),
	ECLIPSE_INSPECT("org.eclipse.jdt.debug.ui.commands.Inspect", "Vox Inspect"),
	ECLIPSE_BREAKPOINT_PROPERTIES("org.eclipse.jdt.debug.ui.breakpoint.properties", "Vox Java Breakpoint Properties"),
	ECLIPSE_NEWRENDERING("org.eclipse.debug.ui.commands.newRendering", "Vox New Rendering"),
	ECLIPSE_NEXTMEMORYBLOCK("org.eclipse.debug.ui.commands.nextMemoryBlock", "Vox Next Memory Monitor"),
	ECLIPSE_MEMORY_NEXTPAGE("org.eclipse.debug.ui.command.nextpage", "Vox Next Page of Memory"),
	ECLIPSE_PREVPAGE("org.eclipse.debug.ui.command.prevpage", "Vox Previous Page of Memory"),
	ECLIPSE_RESUME("org.eclipse.debug.ui.commands.Resume", "Vox Resume"),
	ECLIPSE_RUN_1("org.eclipse.ant.ui.antShortcut.run", "Vox Run Ant Build"),
	ECLIPSE_RUN_2("org.eclipse.pde.ui.runtimeWorkbenchShortcut.run", "Vox Run Eclipse Application"),
	ECLIPSE_RUN_3("org.eclipse.pde.ui.junitWorkbenchShortcut.run", "Vox Run JUnit Plug-in Test"),
	ECLIPSE_RUN_4("org.eclipse.jdt.junit.junitShortcut.run", "Vox Run JUnit Test"),
	ECLIPSE_RUN_5("org.eclipse.jdt.debug.ui.javaAppletShortcut.run", "Vox Run Java Applet"),
	ECLIPSE_RUN_6("org.eclipse.jdt.debug.ui.localJavaShortcut.run", "Vox Run Java Application"),
	ECLIPSE_RUN_7("org.eclipse.pde.ui.EquinoxLaunchShortcut.run", "Vox Run OSGi Framework"),
	ECLIPSE_RUNTOLINE("org.eclipse.debug.ui.commands.RunToLine", "Vox Run to Line"),
	ECLIPSE_RUNLAST("org.eclipse.debug.ui.commands.RunLast", "Vox Run"),
	ECLIPSE_SKIPALLBREAKPOINTS("org.eclipse.debug.ui.commands.SkipAllBreakpoints", "Vox Skip All Breakpoints"),
	ECLIPSE_STEPINTOSELECTION("org.eclipse.jdt.debug.ui.commands.StepIntoSelection", "Vox Step Into Selection"),
	ECLIPSE_STEPINTO("org.eclipse.debug.ui.commands.StepInto", "Vox Step Into"),
	ECLIPSE_STEPOVER("org.eclipse.debug.ui.commands.StepOver", "Vox Step Over"),
	ECLIPSE_STEPRETURN("org.eclipse.debug.ui.commands.StepReturn", "Vox Step Return"),
	ECLIPSE_TERMINATE("org.eclipse.debug.ui.commands.Terminate", "Vox Terminate"),
	ECLIPSE_TOGGLEBREAKPOINT("org.eclipse.debug.ui.commands.ToggleBreakpoint", "Vox Toggle Breakpoint"),
	ECLIPSE_TOGGLEMEMORYMONITORSPANE("org.eclipse.debug.ui.commands.toggleMemoryMonitorsPane",
			"Vox Toggle Memory Monitors Pane"),
	ECLIPSE_TOGGLESTEPFILTERS("org.eclipse.debug.ui.commands.ToggleStepFilters", "Vox Use Step Filters"),
	ECLIPSE_DECLARATIONS_WORKSPACE("org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace",
			"Vox Declaration in Workspace"),
	ECLIPSE_PERFORMTEXTSEARCHWORKSPACE("org.eclipse.search.ui.performTextSearchWorkspace",
			"Vox Find Text in Workspace"),
	ECLIPSE_OPENSEARCHDIALOG("org.eclipse.search.ui.openSearchDialog", "Vox Open Search Dialog"),
	ECLIPSE_REFERENCES_WORKSPACE("org.eclipse.jdt.ui.edit.text.java.search.references.in.workspace",
			"Vox References in Workspace"),
	ECLIPSE_FILE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.search.occurrences.in.file.quickMenu",
			"Vox Show Occurrences in File Quick Menu"),
	ECLIPSE_COMMENT("org.eclipse.jdt.ui.edit.text.java.add.block.comment", "Vox Add Block Comment"),
	ECLIPSE_IMPORT("org.eclipse.jdt.ui.edit.text.java.add.import", "Vox Add Import"),
	ECLIPSE_JAVADOC_COMMENT("org.eclipse.jdt.ui.edit.text.java.add.javadoc.comment", "Vox Add Javadoc Comment"),
	ECLIPSE_CLASSFILE("org.eclipse.jdt.ui.edit.text.java.annotate.classFile", "Vox Annotate Class File"),
	ECLIPSE_INDENT("org.eclipse.jdt.ui.edit.text.java.indent", "Vox Correct Indentation"),
	ECLIPSE_JAVA_FORMAT("org.eclipse.jdt.ui.edit.text.java.format", "Vox Format"),
	ECLIPSE_COMMAND("org.eclipse.ant.ui.open.declaration.command", "Vox Open Declaration"),
	ECLIPSE_OPENEXTERNALDOC("org.eclipse.ant.ui.openExternalDoc", "Vox Open External Documentation"),
	ECLIPSE_IMPORTS("org.eclipse.jdt.ui.edit.text.java.organize.imports", "Vox Organize Imports"),
	ECLIPSE_ASSIST_1("org.eclipse.jdt.ui.correction.assignToField.assist", "Vox Assign to field"),
	ECLIPSE_ASSIST_2("org.eclipse.jdt.ui.correction.assignToLocal.assist", "Vox Assign to local variable"),
	ECLIPSE_ASSIST_3("org.eclipse.jdt.ui.correction.extractMethodInplace.assist", "Vox Extract method"),
	ECLIPSE_ASSIST_4("org.eclipse.jdt.ui.correction.renameInFile.assist", "Vox Rename in file"),
	ECLIPSE_BLOCK_COMMENT("org.eclipse.jdt.ui.edit.text.java.remove.block.comment", "Vox Remove Block Comment"),
	ECLIPSE_ANNOTATIONS("org.eclipse.jdt.ui.edit.text.remove.occurrence.annotations",
			"Vox Remove Occurrence Annotations"),
	ECLIPSE_RENAMEINFILE("org.eclipse.ant.ui.renameInFile", "Vox Rename In File"),
	ECLIPSE_SOURCE_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.source.quickMenu", "Vox Show Source Quick Menu"),
	ECLIPSE_SURROUND_QUICKMENU("org.eclipse.jdt.ui.edit.text.java.surround.with.quickMenu",
			"Vox Surround With Quick Menu"),
	ECLIPSE_ANT_TOGGLEMARKOCCURRENCES("org.eclipse.ant.ui.toggleMarkOccurrences", "Vox Toggle Ant Mark Occurrences"),
	ECLIPSE_TOGGLE_COMMENT("org.eclipse.jdt.ui.edit.text.java.toggle.comment", "Vox Toggle Comment"),
	ECLIPSE_JAVA_TOGGLEMARKOCCURRENCES("org.eclipse.jdt.ui.edit.text.java.toggleMarkOccurrences",
			"Vox Toggle Mark Occurrences"),
	ECLIPSE_LAYOUTSPYCOMMAND("org.eclipse.tools.layout.spy.commands.layoutSpyCommand", "Vox Layout Spy"),
	ECLIPSE_MENUSPYCOMMAND("org.eclipse.pde.runtime.spy.commands.menuSpyCommand", "Vox Plug-in Menu Spy"),
	ECLIPSE_SPYCOMMAND("org.eclipse.pde.runtime.spy.commands.spyCommand", "Vox Plug-in Selection Spy"),
	ECLIPSE_COLLAPSE_ALL("org.eclipse.ui.edit.text.folding.collapse_all", "Vox Collapse All"),
	ECLIPSE_COLLAPSE("org.eclipse.ui.edit.text.folding.collapse", "Vox Collapse"),
	ECLIPSE_COPYLINEDOWN("org.eclipse.ui.edit.text.copyLineDown", "Vox Copy Lines"),
	ECLIPSE_DELETE_LINE("org.eclipse.ui.edit.text.delete.line", "Vox Delete Line"),
	ECLIPSE_DELETENEXTWORD("org.eclipse.ui.edit.text.deleteNextWord", "Vox Delete Next Word"),
	ECLIPSE_DELETEPREVIOUSWORD("org.eclipse.ui.edit.text.deletePreviousWord", "Vox Delete Previous Word"),
	ECLIPSE_END("org.eclipse.ui.edit.text.delete.line.to.end", "Vox Delete to End of Line"),
	ECLIPSE_COPYLINEUP("org.eclipse.ui.edit.text.copyLineUp", "Vox Duplicate Lines"),
	ECLIPSE_EXPAND_ALL("org.eclipse.ui.edit.text.folding.expand_all", "Vox Expand All"),
	ECLIPSE_EXPAND("org.eclipse.ui.edit.text.folding.expand", "Vox Expand"),
	ECLIPSE_SMARTENTERINVERSE("org.eclipse.ui.edit.text.smartEnterInverse", "Vox Insert Line Above Current Line"),
	ECLIPSE_SMARTENTER("org.eclipse.ui.edit.text.smartEnter", "Vox Insert Line Below Current Line"),
	ECLIPSE_LINES("org.eclipse.ui.edit.text.join.lines", "Vox Join Lines"),
	ECLIPSE_GOTO_LINEEND("org.eclipse.ui.edit.text.goto.lineEnd", "Vox Line End"),
	ECLIPSE_GOTO_LINESTART("org.eclipse.ui.edit.text.goto.lineStart", "Vox Line Start"),
	ECLIPSE_MOVELINEDOWN("org.eclipse.ui.edit.text.moveLineDown", "Vox Move Lines Down"),
	ECLIPSE_MOVELINEUP("org.eclipse.ui.edit.text.moveLineUp", "Vox Move Lines Up"),
	ECLIPSE_GOTO_WORDNEXT("org.eclipse.ui.edit.text.goto.wordNext", "Vox Next Word"),
	ECLIPSE_HYPERLINK("org.eclipse.ui.edit.text.open.hyperlink", "Vox Open Hyperlink"),
	ECLIPSE_GOTO_WORDPREVIOUS("org.eclipse.ui.edit.text.goto.wordPrevious", "Vox Previous Word"),
	ECLIPSE_RESTORE("org.eclipse.ui.edit.text.folding.restore", "Vox Reset Structure"),
	ECLIPSE_LINEDOWN("org.eclipse.ui.edit.text.scroll.lineDown", "Vox Scroll Line Down"),
	ECLIPSE_LINEUP("org.eclipse.ui.edit.text.scroll.lineUp", "Vox Scroll Line Up"),
	ECLIPSE_SELECT_LINEEND("org.eclipse.ui.edit.text.select.lineEnd", "Vox Select Line End"),
	ECLIPSE_SELECT_LINESTART("org.eclipse.ui.edit.text.select.lineStart", "Vox Select Line Start"),
	ECLIPSE_SELECT_WORDNEXT("org.eclipse.ui.edit.text.select.wordNext", "Vox Select Next Word"),
	ECLIPSE_SELECT_WORDPREVIOUS("org.eclipse.ui.edit.text.select.wordPrevious", "Vox Select Previous Word"),
	ECLIPSE_SHOWINFORMATION("org.eclipse.ui.edit.text.showInformation", "Vox Show Tooltip Description"),
	ECLIPSE_TEXTEND("org.eclipse.ui.edit.text.goto.textEnd", "Vox Text End"),
	ECLIPSE_TEXTSTART("org.eclipse.ui.edit.text.goto.textStart", "Vox Text Start"),
	ECLIPSE_LOWERCASE("org.eclipse.ui.edit.text.lowerCase", "Vox To Lower Case"),
	ECLIPSE_UPPERCASE("org.eclipse.ui.edit.text.upperCase", "Vox To Upper Case"),
	ECLIPSE_TOGGLE_FOLDING("org.eclipse.ui.edit.text.folding.toggle", "Vox Toggle Folding"),
	ECLIPSE_TOGGLEOVERWRITE("org.eclipse.ui.edit.text.toggleOverwrite", "Vox Toggle Overwrite"),
	ECLIPSE_ZOOMIN("org.eclipse.ui.edit.text.zoomIn", "Vox Zoom In"),
	ECLIPSE_ZOOMOUT("org.eclipse.ui.edit.text.zoomOut", "Vox Zoom Out"),
	ECLIPSE_SEARCHTARGETREPOSITORIES("org.eclipse.pde.ui.searchTargetRepositories",
			"Vox Add Artifact to Target Platform"),
	ECLIPSE_FINDREFERENCES("org.eclipse.ui.genericeditor.findReferences", "Vox Find References"),
	ECLIPSE_SHOWVIEW("org.eclipse.ui.views.showView", "Vox Show View"),
	ECLIPSE_ACTIVATEEDITOR("org.eclipse.ui.window.activateEditor", "Vox Activate Editor"),
	ECLIPSE_NEXTEDITOR("org.eclipse.ui.window.nextEditor", "Vox Next Editor"),
	ECLIPSE_NEXTPERSPECTIVE("org.eclipse.ui.window.nextPerspective", "Vox Next Perspective"),
	ECLIPSE_NEXTVIEW("org.eclipse.ui.window.nextView", "Vox Next View"),
	ECLIPSE_PREVIOUSEDITOR("org.eclipse.ui.window.previousEditor", "Vox Previous Editor"),
	ECLIPSE_PREVIOUSPERSPECTIVE("org.eclipse.ui.window.previousPerspective", "Vox Previous Perspective"),
	ECLIPSE_PREVIOUSVIEW("org.eclipse.ui.window.previousView", "Vox Previous View"),
	ECLIPSE_QUICKACCESS("org.eclipse.ui.window.quickAccess", "Vox Quick Access"),
	ECLIPSE_OPENEDITORDROPDOWN("org.eclipse.ui.window.openEditorDropDown", "Vox Quick Switch Editor"),
	ECLIPSE_SPY("org.eclipse.ui.window.spy", "Vox Show Contributing Plug-in"),
	ECLIPSE_SHOWKEYASSIST("org.eclipse.ui.window.showKeyAssist", "Vox Show Key Assist"),
	ECLIPSE_SHOWRULERCONTEXTMENU("org.eclipse.ui.edit.text.showRulerContextMenu", "Vox Show Ruler Context Menu"),
	ECLIPSE_SHOWSYSTEMMENU("org.eclipse.ui.window.showSystemMenu", "Vox Show System Menu"),
	ECLIPSE_SHOWVIEWMENU("org.eclipse.ui.window.showViewMenu", "Vox Show View Menu"),
	ECLIPSE_SWITCHTOEDITOR("org.eclipse.ui.window.switchToEditor", "Vox Switch to Editor"),
	ECLIPSE_FULLSCREENMODE("org.eclipse.ui.window.fullscreenmode", "Vox Toggle Full Screen"),
	ECLIPSE_SPLITEDITOR("org.eclipse.ui.window.splitEditor", "Vox Toggle Split Editor"),
	ECLIPSE_TASK("org.eclipse.mylyn.tasks.ui.command.openTask", "Vox Open Task"),
	ECLIPSE_GET_SET("org.eclipse.jdt.ui.edit.text.java.create.getter.setter", "Vox Insert Get Set"),
	ECLIPSE_HASH_EQUALS("org.eclipse.jdt.ui.edit.text.java.generate.hashcode.equals", "Vox Insert Hash"),
	ECLIPSE_TO_STRING("org.eclipse.jdt.ui.edit.text.java.generate.tostring", "Vox Insert String"),
	ECLIPSE_CONSTRUCTOR("org.eclipse.jdt.ui.edit.text.java.generate.constructor.using.fields",
			"Vox Insert Constructor"),
	ECLIPSE_ACTION_TERMINATE("org.eclipse.debug.ui.actions.Terminate", "Vox Action Terminate"),
	ECLIPSE_ACTION_RESUME("org.eclipse.debug.ui.actions.Resume", "Vox Action Resume"),
	ECLIPSE_REBUILD("org.eclipse.jdt.ui.index.rebuild", "Vox Rebuild"),
	ECLIPSE_FILE_CLOSE_OTHERS("org.eclipse.ui.file.closeOthers", "Vox Close Others"),
	ECLIPSE_OPEN_WORKSPACE("org.eclipse.ui.file.openWorkspace", "Vox Open Workspace"),
	ECLIPSE_STOP_PLUGIN("stop plugin", "Vox Stop Listening"),
	ECLIPSE_FILE_IMPORT("org.eclipse.ui.file.import", "Vox Import"),
	ECLIPSE_FILE_EXPORT("org.eclipse.ui.file.export", "Vox Export"),
	ECLIPSE_FILE_SAVE_AS("org.eclipse.ui.file.saveAs", "Vox Save As"),
	ECLIPSE_FILE_REVERT("org.eclipse.ui.file.revert", "Vox Revert"),
	ECLIPSE_FILE_RESTART("org.eclipse.ui.file.restartWorkbench", "Vox Restart Workbench"),
	ECLIPSE_FILE_PROPERTIES("org.eclipse.ui.file.properties", "Vox File Properties"),
	ECLIPSE_FILE_EXIT("org.eclipse.ui.file.exit", "Vox File Exit"),
	ECLIPSE_FILE_MOVE("org.eclipse.ui.edit.move", "Vox File Move"),
	ECLIPSE_CONTENT_ASSIST("org.eclipse.ui.edit.text.contentAssist.proposals", "Vox Content Assist"),
	ECLIPSE_ADD_TASK("org.eclipse.ui.edit.addTask", "Vox Add Task"),
	ECLIPSE_ADD_BOOKMARK("org.eclipse.ui.edit.addBookmark", "Vox Add Bookmark"),
	ECLIPSE_NAVIGATE_GO_INTO("org.eclipse.ui.navigate.goInto", "Vox Go Into"),
	ECLIPSE_NAVIGATE_BACK("org.eclipse.ui.navigate.back", "Vox Navigate Back"),
	ECLIPSE_NAVIGATE_FORWARD("org.eclipse.ui.navigate.forward", "Vox Navigate Forward"),
	ECLIPSE_NAVIGATE_UP("org.eclipse.ui.navigate.up", "Vox Up"),
	ECLIPSE_NAVIGATE_LINK_WITH_EDITOR("org.eclipse.ui.navigate.linkWithEditor", "Vox Link With Editor"),
	ECLIPSE_NAVIGATE_SHOW_IN("org.eclipse.ui.navigate.showIn", "Vox Show In"),
	ECLIPSE_NAVIGATE_SHOW_IN_TARGET("org.eclipse.ui.navigate.showIn.targetId", "Vox Show In Target"),
	ECLIPSE_BUILD_PROJECT("org.eclipse.ui.project.buildProject", "Vox Build Project"),
	ECLIPSE_CLOSE_PROJECT("org.eclipse.ui.project.closeProject", "Vox Close Project"),
	ECLIPSE_CLOSE_UNRELATED_PROJECTS("org.eclipse.ui.project.closeUnrelatedProjects", "Vox Close Unrelated Projects"),
	ECLIPSE_PROJECT_OPEN_PROJECT("org.eclipse.ui.project.openProject", "Vox Open Project"),
	ECLIPSE_WINDOW_NEW_WINDOW("org.eclipse.ui.window.newWindow", "Vox New Window"),
	ECLIPSE_WINDOW_NEW_EDITOR("org.eclipse.ui.window.newEditor", "Vox New Editor"),
	ECLIPSE_WINDOW_MAXIMIZE_EDITOR("org.eclipse.ui.window.maximizePart", "Vox Maximize Active View"),
	ECLIPSE_WINDOW_MINIMIZE_EDITOR("org.eclipse.ui.window.minimizePart", "Vox Minimize Active View"),
	ECLIPSE_WINDOW_CLOSE_ALL_PERSPECTIVES("org.eclipse.ui.window.closeAllPerspectives", "Vox Close All Perspectives"),
	ECLIPSE_WINDOW_CLOSE_PERSPECTIVE("org.eclipse.ui.window.closePerspective", "Vox Close Perspective"),
	ECLIPSE_WINDOW_CLOSE_PERSPECTIVE_ID("org.eclipse.ui.window.closePerspective.perspectiveId",
			"Vox Close Perspective id"),
	ECLIPSE_WINDOW_CLOSE_PART("org.eclipse.ui.file.closePart", "Vox Close Part"),
	ECLIPSE_WINDOW_CUSTOMIZE_PERSPECTIVE("org.eclipse.ui.window.customizePerspective", "Vox Customize Perspective"),
	ECLIPSE_WINDOW_PIN_EDITOR("org.eclipse.ui.window.pinEditor", "Vox Pin Editor"),
	ECLIPSE_WINDOW_PREFERENCES("org.eclipse.ui.window.preferences", "Vox Preferences"),
	ECLIPSE_WINDOW_RESET_PERSPECTIVE("org.eclipse.ui.window.resetPerspective", "Vox Reset Perspective"),
	ECLIPSE_WINDOW_SAVE_PERSPECTIVE("org.eclipse.ui.window.savePerspective", "Vox Save Perspective"),
	ECLIPSE_WINDOW_LOCK_TOOLBAR("org.eclipse.ui.window.lockToolBar", "Vox Lock Toolbar"),
	ECLIPSE_HELP_CONTENTS("org.eclipse.ui.help.helpContents", "Vox Help Contents"),
	ECLIPSE_HELP_SEARCH("org.eclipse.ui.help.helpSearch", "Vox Help Search"),
	ECLIPSE_DYNAMIC_HELP("org.eclipse.ui.help.dynamicHelp", "Vox Dynamic Help"),
	ECLIPSE_HELP_WELCOME("org.eclipse.ui.help.quickStartAction", "Vox Help Welcome"),
	ECLIPSE_HELP_TIPS_AND_TRICKS("org.eclipse.ui.help.tipsAndTricksAction", "Vox Help Tips And Tricks"),
	ECLIPSE_HELP_ABOUT("org.eclipse.ui.help.aboutAction", "Vox Help About"),
	ECLIPSE_SHOW_PERSPECTIVE("org.eclipse.ui.perspectives.showPerspective", "Vox Show Perspective"),
	ECLIPSE_SCROLL_DOWN("org.eclipse.ui.edit.text.scroll.lineDown", "Vox Scroll Down");

	private String eclipseId;
	private String actionId;

	private Action(String eclipseId, String actionId) {
		this.eclipseId = eclipseId;
		this.actionId = actionId;
	}

	public String getEclipseId() {
		return this.eclipseId;
	}

	public String getActionId() {
		return this.actionId;
	}

	public String formatCommand() {
		StringBuilder sb = new StringBuilder();
		sb.append(name());
		sb.append(": ");
		sb.append(this.eclipseId);
		return sb.toString();
	}

	public String toString() {
		return formatCommand();
	}
}